[package]
name = "bits_cnt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-std = { version = "0.4.0" }
ark-ff = "0.4.0"
rand = "0.8.5"

[dev-dependencies]
ark-bn254 = "0.4.0"